#ddev-generated
RUN npm install -g \
    grunt \
    grunt-cli \
    grunt-browser-sync \
    grunt-contrib-clean \
    grunt-contrib-cssmin \
    grunt-contrib-imagemin \
    grunt-contrib-jasmine \
    grunt-contrib-less \
    grunt-contrib-watch \
    grunt-eslint \
    grunt-exec \
    grunt-replace \
    grunt-styledocco \
    grunt-template-jasmine-requirejs \
    grunt-text-replace \
    load-grunt-config \
    time-grunt \
    underscore \
    browser-sync
