#!/bin/bash

#ddev-generated
## Description: Run browser-sync and grunt watch in the web container
## Usage: browsersync
## Example: "ddev browsersync"
## ExecRaw: true

echo "Proxying Browsersync on $(echo ${DDEV_PRIMARY_URL} | sed -E 's/:[0-9]+//'):3000"
npx browser-sync start -c /var/www/html/.ddev/browser-sync.cjs & BROWSERSYNC_PID=$!

grunt watch & WATCH_PID=$!

trap "kill $BROWSERSYNC_PID $WATCH_PID 2>/dev/null" EXIT

wait
